// 別案C の PC 画面（1440×900）
import { C, F, SH, icon, obj, tile, earArt, shoeArt, num, label, pill, cond, aiNote, sampleNote, tierMark, voiceStrip, justStrip, repeatLine, voiceTag, searchBox, mark } from './libc.mjs';
import { MAPPED, STATS, AXES, SHORT, LABEL, POLE, neighbors, byShort, yen, KEYS, Q, SHOES, MEASURE, ALL_DIR, WIDE_DIR, WIDE_TOTAL, LIGHT, CUSH, SHOE_REP, SHOE_SHIP, SHOE_BEGIN, shrink, PLACES } from './datac.mjs';
import { swarm } from './screensc.mjs';

const W = 1440, H = 900;
const A = (x, y, html, { w = 0, z = 2 } = {}) => `<div style="position:absolute; left:${x}px; top:${y}px;${w ? ` width:${w}px;` : ''} z-index:${z};">${html}</div>`;
const page = (body) => `<div style="position:relative; width:${W}px; height:${H}px; overflow:hidden; background:${C.paper}; font-family:${F.jp}; color:${C.ink};">${body}</div>`;
const card = (inner, { pad = 20, r = 20 } = {}) => `<div style="box-sizing:border-box; padding:${pad}px; border-radius:${r}px; background:${C.card}; box-shadow:${SH.card};">${inner}</div>`;
const top = (active = '') => A(0, 0, `<div style="width:${W}px; height:72px; box-sizing:border-box; padding:0 48px; display:flex; align-items:center; gap:28px; border-bottom:1px solid ${C.hair}; background:${C.paper};">${mark(18)}${searchBox('商品名・カテゴリ・困りごと・条件の言葉', { w: 520, h: 44 })}<span style="flex:1;"></span><span style="font-size:13px; color:${C.ink2};">わたしの条件</span>${cond('足幅が広い', { on: true, h: 32, fs: 12 })}${cond('敏感肌', { on: true, h: 32, fs: 12 })}<span style="display:flex; gap:18px; font-size:13px;">${['暮らしの場所', '並べる', '保存'].map((t) => `<span style="font-weight:${t === active ? 700 : 500};">${t}</span>`).join('')}</span></div>`);

export function pcHome() {
  const tiles = PLACES.map((pl, i) => `<div style="height:168px; box-sizing:border-box; padding:14px 16px; border-radius:18px; background:${C.card}; box-shadow:${SH.card}; display:flex; flex-direction:column; justify-content:space-between;"><div style="display:flex; gap:0; align-items:flex-end; height:56px;">${pl.objs.map((o) => obj(o, { size: 48 })).join('')}</div><div><b style="font-size:16px;">${pl.name}</b><div style="font-family:${F.mono}; font-size:11px; color:${C.muted}; margin-top:2px;">読めた ${[7, 12, 9, 6, 4, 8, 5, 3, 2, 6][i]} / ${[42, 38, 51, 29, 18, 33, 60, 24, 16, 40][i]}カテゴリ</div><div style="font-size:11px; color:${C.muted}; margin-top:3px; line-height:1.45; height:32px; overflow:hidden;">${pl.units.join('・')}</div></div></div>`).join('');
  const week = [
    ['tag', '化粧水', '段1 になった（8商品・240件）'],
    ['dots', '完全ワイヤレスイヤホン', `地図まで あと${12 - MAPPED.filter((p) => p.read >= 30).length}商品`],
    ['person', 'ランニングシューズ', `幅広と書いた声 ${WIDE_TOTAL}件`],
    ['loop', 'コーヒー', `また買った ${MEASURE.cats[2].rep} / ${MEASURE.cats[2].n}件`],
  ].map(([ic, t, s]) => `<div style="display:flex; gap:12px; align-items:center; padding:12px 0; border-bottom:1px solid ${C.hair};">${tile(icon(ic, { size: 20 }), { w: 40, r: 12 })}<div><div style="font-size:14px; font-weight:700;">${t}</div><div style="font-size:12px; color:${C.ink2}; margin-top:2px;">${s}</div></div></div>`).join('');
  const trouble = ['すぐ壊れた', 'サイズが合わない', '思っていたのと違う', 'においが気になる', '音がうるさい', '手入れが大変'];
  return page(`${top()}
${A(48, 108, `<div style="font-size:34px; font-weight:700; line-height:1.3;">似た人の、買ったあと。</div><div style="font-size:14px; color:${C.ink2}; margin-top:8px;">買った人の声を、どのカテゴリでも同じ読み方で。自分と同じ条件を書いた人の声だけで、数えなおせる</div>`)}
${A(48, 222, `<div style="display:flex; justify-content:space-between; align-items:baseline; width:940px;"><span style="font-size:18px; font-weight:700;">暮らしの場所から</span><span style="font-size:12px; color:${C.muted};">1つのカテゴリは、いくつかの場所に入る</span></div>`)}
${A(48, 258, `<div style="display:grid; grid-template-columns:repeat(5, 176px); gap:15px; width:940px;">${tiles}</div>`)}
${A(48, 640, `<div style="width:940px;"><div style="font-size:18px; font-weight:700; margin-bottom:12px;">困りごとから</div><div style="display:flex; gap:8px; flex-wrap:wrap;">${trouble.map((t) => `<span style="display:inline-flex; align-items:center; gap:6px; height:38px; padding:0 16px; border-radius:19px; background:${C.card}; box-shadow:${SH.card}; font-size:14px;">${icon('alert', { size: 15 })}${t}</span>`).join('')}</div><div style="font-size:12px; color:${C.muted}; margin-top:10px;">系統ごとの共通の観点。読めているカテゴリだけ件数を出す</div></div>`)}
${A(1040, 108, `<div style="width:352px;">${card(`<div style="font-size:16px; font-weight:700; margin-bottom:4px;">今週</div><div style="font-size:12px; color:${C.muted}; margin-bottom:6px;">読めた量が変わったもの</div>${week}<div style="font-size:11px; color:${C.muted}; margin-top:10px;">戻ってくる理由。通知は保存した商品だけ</div>`)}</div>`)}
${A(1040, 560, `<div style="width:352px;">${card(`<div style="display:flex; justify-content:space-between; align-items:baseline;"><span style="font-size:15px; font-weight:700;">読めている深さ</span><span style="font-family:${F.mono}; font-size:11px; color:${C.muted};">物販 ${526} カテゴリ</span></div><div style="display:flex; flex-direction:column; gap:8px; margin-top:12px;">${[[3, 0], [2, 1], [1, 3], [0, 522]].map(([t, n]) => `<div style="display:flex; align-items:center; justify-content:space-between;">${tierMark(t, { size: 's' })}${num(n, { size: 14 })}</div>`).join('')}</div><div style="font-size:11px; color:${C.muted}; margin-top:10px; line-height:1.6;">今の実数：段2＝イヤホン、段1＝見本で測った化粧水・シューズ・コーヒー。場所ごとの件数は将来を描いた見本</div>`)}</div>`)}
`);
}

export function pcCategory({ k = 'fit' } = {}) {
  const on = MAPPED.filter((p) => p.pos[k] + p.neg[k] > 0), off = MAPPED.filter((p) => !(p.pos[k] + p.neg[k]));
  const RW = 700, RH = 420;
  const pts = swarm(on.map((p) => ({ id: p.s, score: shrink(p.pos[k], p.neg[k]), size: Math.round(40 + 30 * Math.sqrt(Math.min(p.pos[k] + p.neg[k], 50) / 50)), thin: p.read < 30 })), { w: RW, h: RH, pad: 30 });
  const nodes = pts.map((q) => `<span style="position:absolute; left:${Math.round(q.x - q.size / 2)}px; top:${Math.round(q.y - q.size / 2)}px; width:${q.size}px; height:${q.size}px; border-radius:50%; background:${C.tile}; display:flex; align-items:center; justify-content:center; box-shadow:${q.id === '821de2ea' ? `0 0 0 3px #fff, 0 0 0 5px ${C.ink}` : 'none'};${q.thin ? ` outline:1px dashed ${C.faint}; outline-offset:2px; opacity:.72;` : ''}">${earArt(q.id, Math.round(q.size * 0.9))}</span>`).join('');
  const offerable = AXES.filter((a) => a.offerable);
  const asp = offerable.map((a) => `<div style="display:flex; justify-content:space-between; align-items:center; height:40px; padding:0 14px; border-radius:12px; background:${a.key === k ? C.ink : 'transparent'}; color:${a.key === k ? '#fff' : C.ink}; font-size:14px; font-weight:${a.key === k ? 700 : 500};"><span>${LABEL[a.key]}</span><span style="font-family:${F.mono}; font-size:11px; opacity:.7;">${a.products}商品</span></div>`).join('') + `<div style="font-size:12px; color:${C.muted}; margin:10px 14px 4px;">棚を作らない観点（理由つき）</div>` + AXES.filter((a) => !a.offerable).map((a) => `<div style="display:flex; justify-content:space-between; height:30px; align-items:center; padding:0 14px; font-size:13px; color:${C.muted};"><span>${LABEL[a.key]}</span><span style="font-family:${F.mono}; font-size:11px;">${a.products < 8 ? `${a.products}商品だけ` : a.separation < 0.35 ? `差が出ない ${a.separation.toFixed(2)}` : `測れた商品 ${a.measured}`}</span></div>`).join('');
  const s = byShort['821de2ea'];
  const thick = MAPPED.filter((p) => p.read >= 30).length;
  return page(`${top()}
${A(48, 100, `<div style="width:300px;"><div style="font-size:12px; color:${C.muted};">外へ ・ 仕事と学び</div><div style="font-size:24px; font-weight:700; margin-top:4px;">完全ワイヤレスイヤホン</div><div style="margin-top:10px;">${tierMark(2)}</div><div style="font-family:${F.mono}; font-size:12px; color:${C.ink2}; margin-top:10px; line-height:1.7;">${STATS.total}商品のうち${STATS.analysed}商品を読んだ<br>のべ${STATS.read}件（重複${STATS.dupRemoved}件を除いた）</div><div style="margin-top:14px;"><div style="display:flex; justify-content:space-between; font-size:12px;"><span>地図まで</span><span style="font-family:${F.mono}; color:${C.muted};">30件以上 ${thick} / 12商品</span></div><div style="height:6px; border-radius:3px; background:${C.rest}; margin-top:6px;"><div style="width:${(thick / 12) * 100}%; height:6px; border-radius:3px; background:${C.ink};"></div></div></div></div>`)}
${A(40, 350, `<div style="width:316px; display:flex; flex-direction:column; gap:2px;"><div style="font-size:13px; font-weight:700; margin:0 14px 6px;">観点</div>${asp}</div>`)}
${A(380, 100, `<div style="width:${RW + 40}px;">${card(`<div style="display:flex; justify-content:space-between; align-items:baseline;"><span style="font-size:18px; font-weight:700;">${LABEL[k]}のものさし</span>${aiNote()}</div><div style="position:relative; width:${RW}px; height:${RH + 40}px; margin-top:8px;"><div style="position:absolute; left:0; right:0; top:${RH / 2}px; border-top:1.5px solid ${C.hair};"></div><div style="position:absolute; left:${RW / 2}px; top:10px; height:${RH - 20}px; border-left:1px dashed ${C.line};"></div><div style="position:absolute; left:0; top:0; width:${RW}px; height:${RH}px;">${nodes}</div><div style="position:absolute; left:0; right:0; bottom:4px; display:flex; justify-content:space-between; font-size:13px; font-weight:700;"><span style="color:${C.negText};">← ${POLE[k].neg}</span><span style="color:${C.muted}; font-weight:500; font-size:12px;">真ん中＝割れている・読めた量が少ない</span><span style="color:${C.posText};">${POLE[k].pos} →</span></div></div><div style="display:flex; align-items:center; gap:8px; margin-top:14px; font-size:12.5px; color:${C.ink2};">ふれていない ${off.length}商品（最下位ではなく別に）${off.map((p) => `<span style="display:inline-flex; width:30px; height:30px; border-radius:50%; background:${C.tile}; align-items:center; justify-content:center;">${earArt(p.s, 26)}</span>`).join('')}<span style="margin-left:auto; font-family:${F.mono}; font-size:11px; color:${C.muted};">まだ読めていない ${STATS.total - STATS.analysed}商品 →</span></div>`, { pad: 20 })}</div>`)}
${A(1140, 100, `<div style="width:252px; display:flex; flex-direction:column; gap:14px;">${voiceTag({ img: earArt(s.s, 110), name: s.name, read: s.read, total: s.reviewCount, lines: [{ kind: 'neg', t: LABEL[k], n: s.neg[k] }, { kind: 'pos', t: LABEL[k], n: s.pos[k] }, { kind: 'neg', t: 'バッテリー', n: s.neg.battery }], w: 252, imgH: 130, sel: true })}${pill('並べるに入れる', { kind: 'light', h: 42, fs: 13, full: true, ic: 'pair' })}<div style="font-size:12px; color:${C.muted}; line-height:1.6;">わたしの条件（足幅・敏感肌）は、このカテゴリには効かない。イヤホンの条件（耳が小さい 等）は、抽出のやり直しの後</div></div>`)}
`);
}

export function pcProduct() {
  const s = byShort['821de2ea'];
  const rows = KEYS.filter((k) => s.pos[k] + s.neg[k] >= 2).sort((a, b) => s.neg[b] - s.neg[a]);
  const near = neighbors(s, 5);
  const reason = (n) => { const same = n.diffs.filter((d) => Math.abs(d.d) < 0.15).map((d) => SHORT[d.k]).slice(0, 2); const diff = n.diffs[0]; return `${same.length ? `近い：${same.join('・')}` : ''}${diff ? `${same.length ? '　' : ''}違う：${SHORT[diff.k]}` : ''}`; };
  const q = Q['821de2ea'];
  const quotes = ['fit', 'anc', 'battery'].map((k) => `<div style="padding:10px 0; border-bottom:1px solid ${C.hair};"><div style="font-size:12px; font-weight:700;">${LABEL[k]}</div>${q[k].neg ? `<div style="font-size:12.5px; line-height:1.6; margin-top:4px;"><span style="color:${C.negText}; font-weight:700;">不満</span>「${q[k].neg}」</div>` : ''}${q[k].pos ? `<div style="font-size:12.5px; line-height:1.6; margin-top:4px;"><span style="color:${C.posText}; font-weight:700;">満足</span>「${q[k].pos}」</div>` : ''}</div>`).join('');
  return page(`${top()}
${A(48, 100, `<div style="width:380px;"><div style="width:380px; height:300px; border-radius:24px; background:${C.tile}; display:flex; align-items:center; justify-content:center;">${earArt(s.s, 240)}</div><div style="font-size:26px; font-weight:700; margin-top:18px;">${s.name}</div><div style="display:flex; justify-content:space-between; align-items:baseline; margin-top:6px;"><span style="font-family:${F.mono}; font-size:12px; color:${C.ink2};">楽天のレビュー ${s.reviewCount}件のうち ${s.read}件を読んだ</span>${num(yen(s.price), { size: 18 })}</div><div style="margin-top:8px;">${aiNote('AIが分類した件数。引用は原文と照合済み')}</div></div>`)}
${A(470, 100, `<div style="width:520px;">${card(`<div style="display:flex; justify-content:space-between; align-items:baseline; margin-bottom:14px;"><span style="font-size:18px; font-weight:700;">声札</span><span style="font-size:12px; color:${C.muted};">不満の多い順・${s.read}件中</span></div><div style="display:flex; flex-direction:column; gap:14px;">${rows.map((k) => voiceStrip({ pos: s.pos[k], neg: s.neg[k], read: s.read, w: 480, h: 9, name: LABEL[k], fs: 13 })).join('')}</div><div style="display:flex; gap:10px; margin-top:20px;">${pill('楽天で見る', { h: 44, fs: 14 })}${pill('Amazonで見る', { kind: 'line', h: 44, fs: 14 })}</div><div style="font-size:11px; color:${C.muted}; margin-top:8px;">購入の案内は声の後に1か所。Amazon は審査の後（資格情報が無い間は出さない）</div>`)}</div>`)}
${A(1030, 100, `<div style="width:362px; display:flex; flex-direction:column; gap:16px;">${card(`<div style="font-size:15px; font-weight:700; margin-bottom:8px;">声が似ているもの</div>${near.map((n) => `<div style="display:flex; gap:10px; align-items:center; padding:8px 0; border-bottom:1px solid ${C.hair};">${tile(earArt(n.p.s, 36), { w: 42, r: 10 })}<div style="min-width:0;"><div style="font-size:13px; font-weight:700;">${n.p.name}</div><div style="font-size:11.5px; color:${C.ink2};">${reason(n)}</div></div></div>`).join('')}`, { pad: 18 })}${card(`<div style="font-size:15px; font-weight:700;">短い引用</div><div style="font-size:11px; color:${C.muted}; margin-top:2px;">原文と照合できたものだけ。満足・不満の区別は見本（抽出のやり直しで付ける）</div>${quotes}`, { pad: 18 })}</div>`)}
`);
}

export function pcAdmin() {
  const R = MEASURE.cats[1].n;
  const rows = [
    ['共通', '思っていたのと違う', '良し悪し', 'イメージどおり ↔ 違った', '—', 'ok'],
    ['共通', '丈夫さ', '良し悪し', '長持ち ↔ すぐ傷んだ', '—', 'ok'],
    ['系統', 'サイズ感', 'ちょうど', '小さめ ・ ちょうど ・ 大きめ', `${ALL_DIR.join(' / ')}`, 'ok'],
    ['系統', '履き心地', '良し悪し', '楽 ↔ 痛い', '—', 'ok'],
    ['固有', 'クッション', '良し悪し', 'やわらかい ↔ 硬い', `${CUSH[0]} / ${CUSH[1]}`, 'ok'],
    ['固有', '軽さ', '良し悪し', '軽い ↔ 重い', `${LIGHT[0]} / ${LIGHT[1]}`, 'warn'],
    ['固有', 'グリップ', '良し悪し', '滑らない ↔ 滑る', '—', 'hold'],
  ];
  const typeSel = (t) => `<span style="display:inline-flex; border:1px solid ${C.line}; border-radius:10px; overflow:hidden; font-size:11.5px;">${['良し悪し', 'ちょうど', '行動'].map((x) => `<span style="padding:4px 8px; background:${x === t ? C.ink : C.card}; color:${x === t ? '#fff' : C.ink2};">${x}</span>`).join('')}</span>`;
  const tr = ([lay, name, t, pole, cnt, st]) => `<div style="display:grid; grid-template-columns:44px 110px 186px 1fr 92px 96px; align-items:center; gap:10px; padding:11px 0; border-bottom:1px solid ${C.hair}; font-size:13px;"><span style="font-family:${F.mono}; font-size:11px; color:${C.muted};">${lay}</span><b>${name}</b>${typeSel(t)}<span style="color:${C.ink2}; font-size:12.5px;">${pole}${st === 'warn' ? `<span style="display:flex; align-items:center; gap:4px; font-size:11.5px; color:${C.negText}; margin-top:3px;">${icon('alert', { size: 13 })}全員が褒める。差が出ない見込み</span>` : st === 'hold' ? `<span style="display:block; font-size:11.5px; color:${C.muted}; margin-top:3px;">保留：レビューでの言及が少ない</span>` : ''}</span><span style="font-family:${F.mono}; font-size:12px;">${cnt}</span><span>${pill(st === 'warn' ? '棚にしない' : st === 'hold' ? '保留' : '承認', { kind: st === 'ok' ? 'dark' : 'line', h: 30, fs: 12 })}</span></div>`;
  const queue = [['ランニングシューズ', '承認待ち', 1], ['化粧水', '承認待ち', 1], ['コーヒー', '承認待ち', 1], ['完全ワイヤレスイヤホン', '承認済み', 2], ['キャットフード', '読めていない', 0], ['スティック掃除機', '読めていない', 0]].map(([n, s, t], i) => `<div style="display:flex; justify-content:space-between; align-items:center; padding:10px 12px; border-radius:12px; background:${i === 0 ? C.card : 'transparent'}; box-shadow:${i === 0 ? SH.card : 'none'};"><div><div style="font-size:13px; font-weight:700;">${n}</div><div style="font-size:11px; color:${C.muted};">${s}</div></div>${tierMark(t, { size: 's' })}</div>`).join('');
  return page(`${A(0, 0, `<div style="width:${W}px; height:64px; box-sizing:border-box; padding:0 40px; display:flex; align-items:center; gap:16px; background:${C.ink}; color:#fff;">${mark(16, { color: '#fff' })}<span style="font-size:13px; opacity:.8;">管理 ・ 観点の承認</span><span style="flex:1;"></span><span style="font-size:12px; opacity:.7;">1単位5分 × 526 ≒ 44時間（推定）</span></div>`)}
${A(24, 92, `<div style="width:240px; display:flex; flex-direction:column; gap:4px;"><div style="font-size:12px; font-weight:700; color:${C.muted}; margin:0 12px 6px;">承認の順番（優先度の高い順）</div>${queue}</div>`)}
${A(288, 92, `<div style="width:830px;">${card(`<div style="display:flex; justify-content:space-between; align-items:baseline;"><span style="font-size:20px; font-weight:700;">ランニングシューズ の観点</span>${sampleNote(`見本：${R}件から単語の規則で数えた件数`)}</div><div style="font-size:12.5px; color:${C.ink2}; margin-top:6px; line-height:1.6;">AI が辞書（共通・着る／履く）から選び、固有を3つまで提案した。<b style="color:${C.ink};">決めるのは人。</b>型（良し悪し・ちょうど・行動）もここで決める</div><div style="display:grid; grid-template-columns:44px 110px 186px 1fr 92px 96px; gap:10px; margin-top:14px; font-size:11px; color:${C.muted}; font-family:${F.mono};"><span>層</span><span>観点</span><span>型</span><span>極の言葉</span><span>件数(見本)</span><span></span></div>${rows.map(tr).join('')}<div style="margin-top:14px; padding:10px 12px; border-radius:12px; background:${C.paper}; font-size:12px; color:${C.ink2}; line-height:1.6;">${icon('close', { size: 14 }).replace('display:block;', 'display:inline-block; vertical-align:-2px; margin-right:4px;')}機械で弾いた提案：ブランド名や型番を含む観点（例：「○○らしい履き心地」）。自由文から観点を発見させない</div>`, { pad: 22 })}</div>`)}
${A(1140, 92, `<div style="width:268px; display:flex; flex-direction:column; gap:14px;">${card(`<div style="font-size:15px; font-weight:700;">条件の辞書</div><div style="font-size:11.5px; color:${C.muted}; margin:2px 0 10px;">レビューの本人が書いた条件</div>${[['足幅が広い', WIDE_TOTAL], ['はじめたばかり', SHOE_BEGIN], ['普段のサイズ', '—']].map(([t, n]) => `<div style="display:flex; justify-content:space-between; align-items:center; padding:7px 0; border-bottom:1px solid ${C.hair}; font-size:13px;"><span style="display:flex; gap:6px; align-items:center;">${icon('person', { size: 14 })}${t}</span><span style="font-family:${F.mono}; font-size:12px;">${n}${typeof n === 'number' ? ` / ${R}` : ''}</span></div>`).join('')}`, { pad: 18 })}${card(`<div style="font-size:15px; font-weight:700;">数えないもの</div><div style="display:flex; justify-content:space-between; font-size:13px; margin-top:10px;"><span style="display:flex; gap:6px; align-items:center;">${icon('truck', { size: 15 })}配送・お店</span><span style="font-family:${F.mono};">${SHOE_SHIP} / ${R}</span></div><div style="display:flex; justify-content:space-between; font-size:13px; margin-top:8px;"><span style="display:flex; gap:6px; align-items:center;">${icon('loop', { size: 15 })}また買った</span><span style="font-family:${F.mono};">${SHOE_REP} / ${R}</span></div><div style="font-size:11.5px; color:${C.muted}; margin-top:8px; line-height:1.55;">また買ったは、使って減るモノでだけ観点にする（シューズは参考）</div>`, { pad: 18 })}${card(`<div style="font-size:15px; font-weight:700;">単位の注意</div><div style="font-size:12px; color:${C.ink2}; line-height:1.6; margin-top:6px;">同じ型（UA チャージド パスート3 EW）が2ページに分かれている。統合キーが要る（未解決）</div>`, { pad: 18 })}</div>`)}
`);
}

export const PC_C = [['CD01-Home', 'PC ホーム（件数は見本）', pcHome], ['CD02-Category', 'PC カテゴリ・段2（イヤホン）', () => pcCategory()], ['CD03-Product', 'PC 商品（イヤホン）', pcProduct], ['CD04-Admin', 'PC 管理：観点の承認', pcAdmin]];
